apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-management-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leave-management-system
  template:
    metadata:
      labels:
        app: leave-management-system
    spec:
      containers:
      - name: leave-management-system
        image: leave-management-system:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: leave-management-system-service
spec:
  selector:
    app: leave-management-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
